// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtiplptitfnvxxduykqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0aXBscHRpdGZudnh4ZHV5a3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzA4NTksImV4cCI6MjA3MDI0Njg1OX0.NCmCLyo3xpIrlvRqRVOC-NB-qO0nTIaQ075VGXQjrwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});